### ISSUE TITLE
TODO requestAnimationFrame polyfill

### ISSUE THREAD

**Issue by sveisvei** [gardr/ext#9]
https://github.com/gardr/ext/blob/master/lib/index.js#L69

**Comment by gregersrygg** [comment]
Has this been solved @sveisvei ?

**Comment by sveisvei** [comment]
No, but IOS6 does not have any notable marketshare to have this fix anymore. 
raf will most like get recommended as well by the "spec".

**Comment by gregersrygg** [comment]
Ok. Seems like it was fixed in iOS 6.1, and iOS 6.0 is only 0,06% of our users.
Allowing raf in the spec has some potential pitfalls, and I'm not convinced it uses as little cpu as some claim. Hope we have time to do some profiling/testing before recommending it in the spec.

**Comment by OleSan** [comment]
With that little percent of our users, we can at least remove the point about it being illegal to use, but still not recommend it? 

> You can not use of requestAnimationFrame as it break features in the host document.

But still have 

> Animation prior to a user interaction must be written using CSS3 Transitions, Transforms and/or Animation

**Comment by gregersrygg** [comment]
@OleSan :+1:
